import React from 'react';
import { PILLARS } from '../data';
import { MonitoringEntry } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ResponsesViewProps {
    entries: MonitoringEntry[];
    user: { email: string; name: string; role: string } | null;
    onEdit: (entry: MonitoringEntry) => void;
    onDelete: (id: string) => void;
    onClear?: () => void;
}

const ResponsesView: React.FC<ResponsesViewProps> = ({ entries, user, onEdit, onDelete, onClear }) => {

    const handleDownloadPDF = (entry: MonitoringEntry) => {
        const doc = new jsPDF();
        const pillar = PILLARS.find(p => p.name === entry.pillarId);
        const indicator = pillar?.indicators.find(i => i.id === entry.indicatorId);

        // Add Header
        doc.setFillColor(15, 23, 42); // slate-900
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text('Imihigo Performance Report', 105, 15, { align: 'center' });

        doc.setFontSize(10);
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, 25, { align: 'center' });
        doc.text(`Submission ID: ${(entry as any)._id || 'N/A'}`, 105, 32, { align: 'center' });

        // Content
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(14);
        doc.text('Submission Details', 14, 55);

        // Use AutoTable for a clean look
        autoTable(doc, {
            startY: 60,
            head: [['Field', 'Value']],
            body: [
                ['Metric Date', entry.month],
                ['Pillar', entry.pillarName || entry.pillarId],
                ['Indicator', indicator?.name || entry.indicatorName],
                ['Achievement', entry.value.toLocaleString()],
                ['Comments', entry.comments || 'No comments provided'],
                ['Submitted By', (entry as any).submittedBy || 'System'],
                ['Date of Submission', new Date(entry.timestamp).toLocaleString()]
            ],
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] } // blue-500
        });

        // Add Footer
        const finalY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text('This is an official performance tracking document generated by Imihigo MS.', 105, finalY, { align: 'center' });

        doc.save(`Submission_${entry.month}_${entry.indicatorId}.pdf`);
    };

    const handleDownloadAllPDF = () => {
        if (entries.length === 0) return;

        const doc = new jsPDF();

        // Add Header
        doc.setFillColor(15, 23, 42); // slate-900
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text('Imihigo Global Performance Report', 105, 15, { align: 'center' });

        doc.setFontSize(10);
        doc.text(`Generated by: ${user?.name || 'Director'} (${user?.role})`, 105, 25, { align: 'center' });
        doc.text(`Total Entries: ${entries.length} | Date: ${new Date().toLocaleString()}`, 105, 32, { align: 'center' });

        // Content
        const tableBody = entries.map(entry => {
            const pillar = PILLARS.find(p => p.name === entry.pillarId);
            const indicator = pillar?.indicators.find(i => i.id === entry.indicatorId);
            return [
                entry.month,
                entry.pillarName || entry.pillarId,
                indicator?.name || entry.indicatorName,
                entry.value.toLocaleString(),
                (entry as any).submittedBy || 'System'
            ];
        });

        autoTable(doc, {
            startY: 50,
            head: [['Month', 'Pillar', 'Indicator', 'Achievement', 'Submitted By']],
            body: tableBody,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] }, // blue-500
            styles: { fontSize: 8 },
            margin: { top: 50 }
        });

        // Add Footer
        const finalY = (doc as any).lastAutoTable.finalY + 20;
        if (finalY < 280) {
            doc.setFontSize(8);
            doc.setTextColor(100, 116, 139);
            doc.text('This document contains the consolidated performance data for all pillars.', 105, finalY, { align: 'center' });
        }

        doc.save(`Global_Performance_Report_${new Date().toLocaleDateString()}.pdf`);
    };

    return (
        <div className="space-y-6 md:space-y-8 animate-in fade-in duration-500">
            <header className="flex justify-between items-end">
                <div>
                    <h1 className="text-2xl md:text-3xl font-extrabold text-slate-900">Recent submission</h1>
                    <p className="mt-1 md:mt-2 text-sm md:text-base text-slate-600 font-medium">Review and manage your reported data.</p>
                </div>
                <div className="flex space-x-3">
                    {entries.length > 0 && (user?.role === 'Planning director' || user?.role === 'Unity director') && (
                        <button
                            onClick={handleDownloadAllPDF}
                            className="px-4 py-2 bg-emerald-50 text-emerald-600 text-xs font-bold uppercase tracking-widest rounded-xl border border-emerald-100 hover:bg-emerald-100 transition-colors flex items-center space-x-2"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            <span>Download All (PDF)</span>
                        </button>
                    )}
                    {entries.length > 0 && onClear && (
                        <button
                            onClick={onClear}
                            className="px-4 py-2 bg-red-50 text-red-600 text-xs font-bold uppercase tracking-widest rounded-xl border border-red-100 hover:bg-red-100 transition-colors"
                        >
                            Clear All
                        </button>
                    )}
                </div>
            </header>

            <div className="bg-white rounded-3xl shadow-xl border border-slate-200 overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-slate-50 border-b border-slate-200">
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Date & Month</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Indicator</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Submitted By</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">Achievement</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">Target</th>
                                <th className="px-6 py-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {entries.length === 0 ? (
                                <tr>
                                    <td colSpan={5} className="px-6 py-12 text-center">
                                        <div className="flex flex-col items-center opacity-20">
                                            <svg className="w-12 h-12 mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8-4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
                                            </svg>
                                            <p className="text-sm font-black uppercase tracking-tight">No submissions found</p>
                                        </div>
                                    </td>
                                </tr>
                            ) : (
                                entries.map((entry, idx) => {
                                    const pillar = PILLARS.find(p => p.name === entry.pillarId);
                                    const indicator = pillar?.indicators.find(i => i.id === entry.indicatorId);
                                    const fixedTarget = indicator?.targets ? indicator.targets[entry.quarterId as keyof typeof indicator.targets] : 0;

                                    return (
                                        <tr key={idx} className="hover:bg-slate-50 transition-colors group">
                                            <td className="px-6 py-4">
                                                <div className="flex flex-col">
                                                    <span className="text-xs font-bold text-slate-900">{entry.month}</span>
                                                    <span className="text-[10px] text-slate-400 font-medium">{new Date(entry.timestamp).toLocaleDateString()}</span>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="max-w-md">
                                                    <p className="text-xs font-bold text-slate-800 leading-snug">{indicator?.name || entry.indicatorName}</p>
                                                    <p className="text-[10px] text-slate-500 mt-0.5">{entry.pillarName || entry.pillarId}</p>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="flex flex-col">
                                                    <span className="text-[9px] text-slate-400 font-black uppercase tracking-tighter mb-1">Submitted by:</span>
                                                    <span className="text-[10px] font-bold text-slate-600 bg-slate-100 px-2 py-1 rounded-md w-fit">
                                                        {(entry as any).submittedBy || 'System'}
                                                    </span>
                                                    {(user?.role === 'Planning director' || user?.role === 'Unity director') && (
                                                        <span className="text-[8px] font-black text-blue-500 uppercase tracking-tighter mt-1 ml-1">Verified Submitter</span>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                <span className="text-sm font-black text-blue-600">{entry.value.toLocaleString()}</span>
                                            </td>
                                            <td className="px-6 py-4 text-right">
                                                <span className="text-xs font-bold text-red-600">{fixedTarget || 0}</span>
                                            </td>
                                            <td className="px-6 py-4">
                                                <div className="flex items-center justify-center space-x-2">
                                                    <button
                                                        onClick={() => onEdit(entry)}
                                                        className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                                        title="Edit Submission"
                                                    >
                                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                                        </svg>
                                                    </button>
                                                    <button
                                                        onClick={() => handleDownloadPDF(entry)}
                                                        className="p-2 text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors"
                                                        title="Download PDF"
                                                    >
                                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                                        </svg>
                                                    </button>
                                                    <button
                                                        onClick={() => (entry as any)._id && onDelete((entry as any)._id)}
                                                        className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                                        title="Delete Submission"
                                                    >
                                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                        </svg>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    );
                                })
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default ResponsesView;
